project_id = "otiqppcuvvpsaxacnzwi"
[functions.moderate-upload]
enabled = true
verify_jwt = false
import_map = "./functions/moderate-upload/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/moderate-upload/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/moderate-upload/*.html" ]

[functions.push-test]
enabled = true
verify_jwt = false
import_map = "./functions/push-test/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/push-test/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/push-test/*.html" ]

[functions.push-sender]
enabled = true
verify_jwt = false
import_map = "./functions/push-sender/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/push-sender/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/push-sender/*.html" ]
